name: Trivy Kubernetes Manifest Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan on Kubernetes manifests
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config' # Scan for misconfigurations in IaC
          input: 'manifests/' # Path to your Kubernetes manifest directory
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1' # Fail the workflow if high/critical issues are found

      - name: Upload Trivy scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'